app:
  name: "user-service"
  version: "1.0.0"

grpc:
  port: 50052
  timeout: 30

logger:
  level: "debug"

token:
  secret: "my-secret-key"

postgres:
  port: 5432
  pg_user: "postgres"
  pg_password: "password"
  pg_host: "localhost"
  pg_db_name: "postgres"
  db_max_connections: 2
  db_connection_timeout: 30s

migrations:
  path: "./migrations"


